services:
  product.api:
    build:
      context: .
      dockerfile: product.api/Dockerfile
      target: final
    ports:
      - 5224:5224
      - 5334:5334
    networks:
      - proxyInternal
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  order.api:
    build:
      context: .
      dockerfile: order.api/Dockerfile
      target: final
    ports:
      - 5225:5225
      - 5335:5335

    networks:
      - proxyInternal
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  gateway.api:
    build:
      context: .
      dockerfile: gateway.api/Dockerfile
      target: final
    ports:
      - 5226:5226
      - 5336:5336

    networks:
      - proxyInternal
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

networks:
  proxyInternal:
